### ISSUE TITLE
ValidationError: "alg" is not allowed

### ISSUE THREAD

**Issue by Jokero** [auth0/node-jsonwebtoken#213]
jsonwebtoken - 7.0.0

From documentation to **jwt.sign**:

`options`:
* `algorithm` or `alg` (default: `HS256`)

Ok, I want to use `alg` because this is the name of the field with algorithm in the standard.

Let's try:
```js
var jsonwebtoken = require('jsonwebtoken');

var payload = {
    iat: Date.now() / 1000,
    name: 'Dmitry'
};

var secret = 'verystrongsecret';

var token = jsonwebtoken.sign(payload, secret, { alg: 'HS256' });
```

Output:
```
/home/dmitry/dev/node_modules/jsonwebtoken/sign.js:55
    throw err;
    ^

ValidationError: "alg" is not allowed
    at Object.exports.process (/home/dmitry/dev/node_modules/joi/lib/errors.js:140:17)
    at internals.Any.validate (/home/dmitry/dev/node_modules/joi/lib/any.js:667:25)
    at Object.module.exports [as sign] (/home/dmitry/dev/node_modules/jsonwebtoken/sign.js:86:47)
    at Object.<anonymous> (/home/dmitry/dev/test.js:498:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

You can play with it here https://tonicdev.com/5751877c455d971300805e52/575930ec7123801300cdade1

**Comment by FdezRomero** [comment]
I had the same issue. Either fix the code or at least remove it from the docs.

**Comment by jfromaniello** [comment]
Sorry about that and thank you for reporting it.

**Comment by FdezRomero** [comment]
Thanks @jfromaniello! :+1:

**Comment by victorpictor** [comment]
Here we have the RFC https://tools.ietf.org/html/rfc7519

Valid JWT token that can be verified with PyJWT:

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJrZXlWZXJzaW9uIjoiZ3Vlc3RzZXJ2aWNlcy9nc192MS5wdWIiLCJ2ZXJzaW9uIjoiMi4wIiwiaWRwIjoiR29vZ2xlIiwiaWF0IjoxNTAyMzE3MDY3LCJwcm9wZXJ0eUlkIjoxMzMzNDIyMzYsImV4cCI6MTUwMjMxNzE4NywiYXBwbGljYXRpb25JZCI6InBtcy50YXNrLmltcG9ydGVyIn0.P4XSGF9GXk2IjSTOHgUW_erSLclw62QUYVSS2qVY-DCMglRnx5n2KgDq01emoTR7_foFWVHsiA9OuMefCgftDmJRHMty53HxPldBCWdTukoWlXxR8JNISuak9GKa0B1ebBTBn5wqMsDRx1GscouX-uxGfz3aMVnJllnsfGtW0t8

-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGDl/4E9meI6jfszZQtdysi0xQxZ
2ltpdTMx05lCLjuivYSXKRSpcUG2/uY1GSJHDPadzCCyiEMBD5x19dJc4npFtJ+z
WXIbxRNmHOAM6wyo0W7rGhhXdwlH2RMLpdirQNVV92kqrA1qh6uqMXdjyhuaZHNz
j6Myq7WHrBiGvwTtAgMBAAE=
-----END PUBLIC KEY-----
```

Validating it in node js using this lib:

```
node_modules/jsonwebtoken/sign.js:66
    throw err;
    ^
ValidationError: "alg" is not allowed
```

Question:
Why "alg" is a not an allowed key in header? I see most of the libraries used for token signing follow RFC.  Not all the time is used same library to sign and verify, in my case we have apps implemented in py, java, and node.
