### ISSUE TITLE
Generates the same token string each time

### ISSUE THREAD

**Issue by EvanBurbidge** [auth0/node-jsonwebtoken#223]
I've been working with this for a login system and have found its generating the same string each time. Makes storing it in a db for verification a bit of a pain.

**Comment by l0oky** [comment]
I have the exact same issue.

```javascript
// Payload
 { uuid: '6e9bb497-8245-47d4-9f88-790344b5177d',
  role: -1,
  requests: 1,
  ttu: 10,
  ttl: 60,
  iat: 1467305386,
  exp: 1467305446,
  iss: 'test' } 
// Options, should expire in 60 seconds
{ issuer: 'test', algorithm: 'HS512', expiresIn: 60 }
```

**Comment by jfromaniello** [comment]
You can add a `jti` claim with something random and you will get a different token every time.

> Makes storing it in a db for verification a bit of a pain.

You don't need to store the token in the db in order to verify it. Just use `jwt.verify`.

**Comment by l0oky** [comment]
Hi @jfromaniello, I tried your advice:

```bash
# notice jwtid
> jwt.sign({ uuid: 'cf75715c-6c8a-4ce6-b7fd-ebaa7019fc57', role: -1, requests: 1, ttu: 10, ttl: 60 }, { issuer: 'test', jwtid: 'jwtid', algorithm: 'HS512', expiresIn: 60 }, function(e, jwt) { console.log(e, jwt); });
ValidationError: "value" must be an object
    at Object.exports.process (/home/l0oky/Projects/nodejs/src/prati.ba/api/node_modules/joi/lib/errors.js:140:17)
    at internals.Any.validate (/home/l0oky/Projects/nodejs/src/prati.ba/api/node_modules/joi/lib/any.js:667:25)
    at Object.module.exports [as sign] (/home/l0oky/Projects/nodejs/src/prati.ba/api/node_modules/jsonwebtoken/sign.js:86:47)
    at repl:1:5
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
```

**Comment by jfromaniello** [comment]
@l0oky the second argument is the secret

```
> jwt.sign({ uuid: 'cf75715c-6c8a-4ce6-b7fd-ebaa7019fc57', role: -1, requests: 1, ttu: 10, ttl: 60 }, 'test', { issuer: 'test', jwtid: 'jwtid', algorithm: 'HS512', expiresIn: 60 }, function(e, jwt) { console.log(e, jwt); });
undefined
> null 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiY2Y3NTcxNWMtNmM4YS00Y2U2LWI3ZmQtZWJhYTcwMTlmYzU3Iiwicm9sZSI6LTEsInJlcXVlc3RzIjoxLCJ0dHUiOjEwLCJ0dGwiOjYwLCJpYXQiOjE0NjczMDY5MjcsImV4cCI6MTQ2NzMwNjk4NywiaXNzIjoidGVzdCIsImp0aSI6Imp3dGlkIn0.kAsUT-KKpJzwIxKFsET6zcpxiKHcy9PPrCtRYTq1dl357kU2RCwiXu0zu_33WS91K6_8oyrsxmntCsFiDP_llQ'
```

**Comment by l0oky** [comment]
Yes, sorry about that.
