### ISSUE TITLE
RS and ES algorithms doesn't work in nodejs

### ISSUE THREAD

**Issue by davidtt80** [auth0/node-jsonwebtoken#229]
Only HS256, HS348 and HS512 works in node js.(i'm using node js 6.x)
and RS256, RS348, RS512, ES256, ES348 and ES512 doesn't work.

**the following code is right:**

return jwt.sign({ foo : "bar"}, "MY_SECRET", { algorithm: 'HS512'}, function(err, token) {
    console.log(token);
  });

**but this code logs "undefined" and  return an empty object (for all RS and ES algorithms):**

return jwt.sign({ foo : "bar"}, "MY_SECRET", { algorithm: 'RS512'}, function(err, token) {
    console.log(token);
  });

**Comment by jfromaniello** [comment]
It does work but `MY_SECRET` is not a valid certificate. 

The callback is returning an error and not a token.

**Comment by davidtt80** [comment]
@jfromaniello 

MY_SECRET is an example, i will change it with a variable from database later.

according to docs The callback returning an error and a token
// sign asynchronously
jwt.sign({ foo: 'bar' }, cert, { algorithm: 'RS256' }, function(err, token) {
  console.log(token);
});

but this isn't my problem. please see the picture...
![jwtproblem](https://cloud.githubusercontent.com/assets/20221989/16883550/bf88057e-4ad9-11e6-8a23-5988ad7e08d0.jpg)

**Comment by davidtt80** [comment]
@jfromaniello 
this error is returning:

error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Sign.sign (crypto.js:276:26)
    at Object.sign (C:\Apps\node_modules\jwa\index.js:54:45)
    at jwsSign (C:\Apps\node_modules\jws\lib\sign-stream.js:23:24)
    at SignStream.sign (C:\Apps\node_modules\jws\lib\sign-stream.js:49:21)
    at SignStream.<anonymous> (C:\Apps\node_modules\jws\lib\sign-stream.js:37:12)
    at DataStream.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at DataStream.emit (events.js:185:7)
    at DataStream.<anonymous> (C:\Apps\node_modules\jws\lib\data-stream.js:32:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by jfromaniello** [comment]
Thats expected. It will not work with an opaque secret. For asymmetric
signatures you need a valid certificate, the secret is a cert.

You can check the test folder for more examples.
