### ISSUE TITLE
exp header is not set on version 5.4.0

### ISSUE THREAD

**Issue by NikosEfthias** [auth0/node-jsonwebtoken#251]
on `jsonwebtoken@5.4.0` neither of the configs a wrote below adds the `exp`  field into the header
```js
				 jwt.sign(user, authConfig.secret, {
					expiresIn: '12h'
				});
				 jwt.sign(user, authConfig.secret, {
					expiresIn: (Date.now()+1000*60*60*12)
				});
```

**Comment by jfromaniello** [comment]
It actually does
```
oss/node-jsonwebtoken - [v5.4.0] » node
> var jwt = require('./')
undefined
> jwt.decode(jwt.sign({test:'test'},'secret', {expiresIn: '10s'}))
{ test: 'test', iat: 1475851623, exp: 1475851633 }
```

Unless your `user` variable is an string, in that case there is no way to properly encode the `exp` field because there is no way to represent a property inside an string in json.

```
> jwt.decode(jwt.sign('test','secret', {expiresIn: '10s'}))
'test'
```

We acknowledge that this was confusing because we got a lot of people asking this, so newer versions of this library just throw an error if you try to do that, eg:

```
> jwt.decode(jwt.sign('test','secret', {expiresIn: '10s'}))
Error: invalid expiresIn option for string payload
    at Object.module.exports [as sign] (/Users/jose/Projects/oss/node-jsonwebtoken/sign.js:79:22)
    at repl:1:16
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
```
