### ISSUE TITLE
can't sign with RS256 algorithm

### ISSUE THREAD

**Issue by pangz1** [auth0/node-jsonwebtoken#270]
I can't sign with RS256 algorithm, it cause 
`Error: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long`.
Here is my code

```
* generateAccessToken(id) {
        const claims = {
            'sub': id,
            'iss': 'api.site.com',
            'admin': this.admin,
            'username': this.username
        }
        return JWTs.sign(claims, process.env.PRIVATE_KEY, {expiresIn: '24h', algorithm: 'RS256'});
}```

if I remove the algorithm option, it works fine. but I can't verify with my public key, it's always invalid signature

```let token = this.cookies.get('access_token');
 const pubKey = process.env.PUBLIC_KEY;
// because i can't sign with algorithm: 'RS256', so i use the default algorithm to verify the token
JWTs.verify(
    token, 
    pubKey,
    { algorithms: ['HS256'] },
    (err, decoded) => {
        if(err) {
            console.log(err);   // invalid signature
        }
        console.log('decoded', decoded);
})```

I can't figure out how to make it work.

**Comment by elbuo8** [comment]
In your `generateAccessToken` you are signing with `RS256` and in your second snippet you are using `HS256`. You must use both on `RS256`. Also, make sure that your `process.env.PRIVATE_KEY` is valid.

Sorry if I misunderstood but the comments show one thing while the code shows another. It's confusing.

**Comment by ziluvatar** [comment]
@pangz1 I will close this issue, if you are still having problems be free to re-open it.

**Comment by ppicom** [comment]
Hi! This issue is rather old, but I have stumbled upon the same error. I'm trying to generate a JWT encoded with RS256, but I can't get to make it work.

This logs a JWT correctly to the console:

```typescript
this._token = jwt.sign({payload: true}, 'secretkey')
console.log('token', this._token);
```
```
token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp0cnVlLCJpYXQiOjE2MTEwNTU2MDV9.Wk_Z4e4dawE7SquW7FcCoykRuf-NVgusbmLVgcdmzI4
```
<hr>
But when I try to encode it using RS256 I can't get to log the token. Even when debugging, `_token` is always undefined. I've tried several approaches, I'll list them all.

# Synchronous approach

```typescript
// first try in synchronously encoding
this._token = jwt.sign(
      {payload: true},
      'secretkey',
      {algorithm: 'RS256'}
    );
console.log('token', this._token);
```
This does nothing, no logs, no error throwing.

# Async approach through the callback
```typescript
jwt.sign(
      {payload: true},
      'secretkey',
      {algorithm: 'RS256'},
      (err, token) => {
        if (err)
          console.log(err);
        this._token = token;
        console.log('token', token);
      }
    );
```
This returns the following error:
```log
Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:110:29)
    at Object.sign (/home/ppicom/repos/smartdream/biku/biku-firebase/functions/node_modules/jsonwebtoken/node_modules/jwa/index.js:152:45)
    at jwsSign (/home/ppicom/repos/smartdream/biku/biku-firebase/functions/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:32:24)
    at SignStream.sign (/home/ppicom/repos/smartdream/biku/biku-firebase/functions/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:58:21)
    at SignStream.<anonymous> (/home/ppicom/repos/smartdream/biku/biku-firebase/functions/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:46:12)
    at Object.onceWrapper (events.js:420:28)
    at DataStream.emit (events.js:314:20)
    at DataStream.EventEmitter.emit (domain.js:486:12)
    at DataStream.<anonymous> (/home/ppicom/repos/smartdream/biku/biku-firebase/functions/node_modules/jsonwebtoken/node_modules/jws/lib/data-stream.js:32:12)
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

# Async approach, wrapping the method with a promise
```typescript
this._token = await new Promise<string>((resolve, reject) => {
      jwt.sign(
        {payload: true},
        'secretkey',
        {algorithm: 'RS256'},
        (err, token) => {
          if (err) {
            console.log(err);
            reject(err);
          }
          resolve(token!);
        }
      );
    });

    console.log('token', this._token);
```
This returns the same error as in the previous approach:
```log
Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:110:29)
    at Object.sign (/home/ppicom/repos/smartdream/biku/biku-firebase/functions/node_modules/jsonwebtoken/node_modules/jwa/index.js:152:45)
    at jwsSign (/home/ppicom/repos/smartdream/biku/biku-firebase/functions/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:32:24)
    at SignStream.sign (/home/ppicom/repos/smartdream/biku/biku-firebase/functions/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:58:21)
    at SignStream.<anonymous> (/home/ppicom/repos/smartdream/biku/biku-firebase/functions/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:46:12)
    at Object.onceWrapper (events.js:420:28)
    at DataStream.emit (events.js:314:20)
    at DataStream.EventEmitter.emit (domain.js:486:12)
    at DataStream.<anonymous> (/home/ppicom/repos/smartdream/biku/biku-firebase/functions/node_modules/jsonwebtoken/node_modules/jws/lib/data-stream.js:32:12)
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

**Comment by panva** [comment]
RS256 is an [RSA-based algorithm](https://tools.ietf.org/html/rfc7518#section-3.3) identifier. You cannot sign using RS256 with a symmetric secret such as 'secretkey' that your code shows. You need a private RSA key representation instead of a symmetric secret. Symmetric secrets can only be used for [HMAC-based algorithms](https://tools.ietf.org/html/rfc7518#section-3.2), such as HS256.

**Comment by ppicom** [comment]
Thanks for this super quick response @panva. So, that is going to be the error returned when the secret is invalid?

**Comment by panva** [comment]
> Thanks for this super quick response @panva. So, that is going to be the error returned when the secret is invalid?

If you want to work with *secrets* you gotta use HMAC based algorithms. The moment you wish to use RSA-based algorithms, you gotta work with *keys*, private or public, depending on the operation.

In your case you're passing a secret where you should be passing a private key representation.

From the docs:

> `secretOrPrivateKey` is a string, buffer, or object containing either the secret for HMAC algorithms or the PEM encoded private key for RSA and ECDSA.

What algorithms falls into what category is either in the [JWA specification](https://tools.ietf.org/html/rfc7518), or, again, the [docs](https://github.com/auth0/node-jsonwebtoken#algorithms-supported).
