### ISSUE TITLE
Getting "TypeError: this is not a typed array." on jwt.verify()

### ISSUE THREAD

**Issue by TarekDeeb** [auth0/node-jsonwebtoken#282]
Hey guys.
I'm migrating my dev environment to prod. I created everything the same way I did on my production, except that the prod has https instead of http. 

`jwt.sign(obj, 'secretekey', {expiresIn: '365d'})` returns a token, but when I want to use it, I'm getting `TypeError: this is not a typed array.` when doing `jwt.verify(token, 'secretekey')` .

I validated that it was from this function call from the stack trace that i got in the callback function `jwt.verify(token, 'secretekey', function(err,decoded) { // }`

Might it be an issue with https encryption? Should i load pem files in `sign()`? Any light on the matter is greatly appreciated. Thanks!

stack trace in question

```
TypeError: this is not a typed array.
at Function.from (native)
at Object.verify (PATH_TO_APP/node_modules/jwa/index.js:43:31)
at Object.jwsVerify [as verify] (PATH_TO_APP/node_modules/jws/lib/verify-stream.js:54:15)
at Object.JWT.verify (PATH_TO_APP/node_modules/jsonwebtoken/index.js:213:17)
at PATH_TO_APP/app.js:38:22
at Layer.handle [as handle_request] (PATH_TO_APP/node_modules/express/lib/router/layer.js:95:5)
at next (PATH_TO_APP/node_modules/express/lib/router/route.js:131:13)
at Route.dispatch (PATH_TO_APP/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (PATH_TO_APP/node_modules/express/lib/router/layer.js:95:5)
at PATH_TO_APP/node_modules/express/lib/router/index.js:277:22
at param (PATH_TO_APP/node_modules/express/lib/router/index.js:349:14)
at param (PATH_TO_APP/node_modules/express/lib/router/index.js:365:14)
at Function.process_params (PATH_TO_APP/node_modules/express/lib/router/index.js:410:3)
at next (PATH_TO_APP/node_modules/express/lib/router/index.js:271:10)
at PATH_TO_APP/node_modules/express-validator/lib/express_validator.js:291:5
at Layer.handle [as handle_request] (PATH_TO_APP/node_modules/express/lib/router/layer.js:95:5)
```

EDIT: I fixed it by updating my node version on the prod machine. Which is weird because I had the exact same version on my dev machine.

**Comment by ziluvatar** [comment]
Just a matter of curiosity, what version did you have in prod before and after the fix?

**Comment by TarekDeeb** [comment]
Sorry it took long to reply. The version was `4.2.6` and updated to `5.12.0`

**Comment by ziluvatar** [comment]
Weird, I'll have it in mind. Not sure if the SO difference could affect, in that case I guess it could be more about node + so, just wondering.

Thanks for your reply @TarekDeeb !
