### ISSUE TITLE
Cannot sign asynchronously

### ISSUE THREAD

**Issue by ProductOfAmerica** [auth0/node-jsonwebtoken#362]
```
jwt.sign({ foo: 'bar' }, "somerandomstring", { algorithm: 'RS256' }, function(err, token) {
  console.log(err); //error below
  console.log(token); // undefined
});
```

The error produced by `console.log(err)`:
```
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Sign.sign (crypto.js:283:26)
    at Object.sign (C:\Users\......\node_modules\jwa\index.js:55:45)
    at jwsSign (C:\Users\......\node_modules\jws\lib\sign-stream.js:23:24)
    at SignStream.sign (C:\Users\......\node_modules\jws\lib\sign-stream.js:49:21)
    at SignStream.<anonymous> (C:\Users\......\node_modules\jws\lib\sign-stream.js:37:12)
    at DataStream.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at DataStream.emit (events.js:185:7)
    at DataStream.<anonymous> (C:\Users\......\node_modules\jws\lib\data-stream.js:32:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ziluvatar** [comment]
Hi @ProductOfAmerica, you need to pass your private key PEM encoded instead of a string secret.

From README:
>jwt.sign(payload, secretOrPrivateKey, [options, callback])
>
>secretOrPrivateKey is a string, buffer, or object containing either the secret for HMAC algorithms or the PEM encoded private key for RSA and ECDSA. In case of a private key with passphrase an object { key, passphrase } can be used (based on crypto documentation), in this case be sure you pass the algorithm option.
