### ISSUE TITLE
TypeError: crypto.createHmac is not a function

### ISSUE THREAD

**Issue by rajnishcoder** [auth0/node-jsonwebtoken#434]
I tried to use `jsonwebtoken` in `Angular 2` get the **EXCEPTION** below

My Code
```
import * as jwt from 'jsonwebtoken';

ngOnInit() {
        var token = jwt.sign({ foo: 'bar' }, 'mySecretKey');
        var older_token = jwt.sign({ foo: 'bar', iat: Math.floor(Date.now() / 1000) - 30 }, 'mySecretKey')
    }
```

[source](https://www.npmjs.com/package/jsonwebtoken)

**ERROR**

```
EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: crypto.createHmac is not a function
TypeError: crypto.createHmac is not a function
    at Object.sign (webpack-internal:///../../../../jwa/index.js:34:23)
    at Object.jwsSign [as sign] (webpack-internal:///../../../../jws/lib/sign-stream.js:23:24)
    at Object.module.exports [as sign] (webpack-internal:///../../../../jsonwebtoken/sign.js:186:16)
    at CheckIMEIStatusComponent.ngOnInit (webpack-internal:///../../../../../src/app/components/check-imei-status/check-imei-status.component.ts:26:25)
    at Wrapper_CheckIMEIStatusComponent.ngDoCheck (/ComponentsModule/CheckIMEIStatusComponent/wrapper.ngfactory.js:22:53)
    at CompiledTemplate.proxyViewClass.View_CheckIMEIStatusComponent_Host0.detectChangesInternal (/ComponentsModule/CheckIMEIStatusComponent/host.ngfactory.js:28:38)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (webpack-internal:///../../../core/src/linker/view.js:438:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (webpack-internal:///../../../core/src/linker/view.js:633:44)
    at ViewRef_.detectChanges (webpack-internal:///../../../core/src/linker/view_ref.js:175:20)
    at RouterOutlet.activate (webpack-internal:///../../../router/src/directives/router_outlet.js:160:42)
    at ActivateRoutes.placeComponentIntoOutlet (webpack-internal:///../../../router/src/router.js:1359:16)
    at ActivateRoutes.activateRoutes (webpack-internal:///../../../router/src/router.js:1326:26)
    at eval (webpack-internal:///../../../router/src/router.js:1262:58)
    at Array.forEach (<anonymous>)
    at ActivateRoutes.activateChildRoutes (webpack-internal:///../../../router/src/router.js:1262:29)
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:233
Zone.runGuarded @ zone.js:129
_loop_1 @ zone.js:416
drainMicroTaskQueue @ zone.js:425
Promise resolved (async)
scheduleQueueDrain @ zone.js:378
scheduleMicroTask @ zone.js:386
ZoneDelegate.scheduleTask @ zone.js:245
Zone.scheduleMicroTask @ zone.js:165
scheduleResolveOrReject @ zone.js:507
resolvePromise @ zone.js:470
(anonymous) @ zone.js:449
webpackJsonpCallback @ inline.bundle.js:22
(anonymous) @ components.module.chunk.js:1
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:233
Zone.runGuarded @ zone.js:129
_loop_1 @ zone.js:416
drainMicroTaskQueue @ zone.js:425
Promise resolved (async)
scheduleQueueDrain @ zone.js:378
scheduleMicroTask @ zone.js:386
ZoneDelegate.scheduleTask @ zone.js:245
Zone.scheduleMicroTask @ zone.js:165
scheduleResolveOrReject @ zone.js:507
resolvePromise @ zone.js:470
(anonymous) @ zone.js:449
webpackJsonpCallback @ inline.bundle.js:22
(anonymous) @ components.module.chunk.js:1
error_handler.js:60 Error: Uncaught (in promise): Error: Error in :0:0 caused by: crypto.createHmac is not a function
TypeError: crypto.createHmac is not a function
    at Object.sign (webpack-internal:///../../../../jwa/index.js:34:23)
    at Object.jwsSign [as sign] (webpack-internal:///../../../../jws/lib/sign-stream.js:23:24)
    at Object.module.exports [as sign] (webpack-internal:///../../../../jsonwebtoken/sign.js:186:16)
    at CheckIMEIStatusComponent.ngOnInit (webpack-internal:///../../../../../src/app/components/check-imei-status/check-imei-status.component.ts:26:25)
    at Wrapper_CheckIMEIStatusComponent.ngDoCheck (/ComponentsModule/CheckIMEIStatusComponent/wrapper.ngfactory.js:22:53)
    at CompiledTemplate.proxyViewClass.View_CheckIMEIStatusComponent_Host0.detectChangesInternal (/ComponentsModule/CheckIMEIStatusComponent/host.ngfactory.js:28:38)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (webpack-internal:///../../../core/src/linker/view.js:438:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (webpack-internal:///../../../core/src/linker/view.js:633:44)
    at ViewRef_.detectChanges (webpack-internal:///../../../core/src/linker/view_ref.js:175:20)
    at RouterOutlet.activate (webpack-internal:///../../../router/src/directives/router_outlet.js:160:42)
    at ActivateRoutes.placeComponentIntoOutlet (webpack-internal:///../../../router/src/router.js:1359:16)
    at ActivateRoutes.activateRoutes (webpack-internal:///../../../router/src/router.js:1326:26)
    at eval (webpack-internal:///../../../router/src/router.js:1262:58)
    at Array.forEach (<anonymous>)
    at ActivateRoutes.activateChildRoutes (webpack-internal:///../../../router/src/router.js:1262:29)
    at resolvePromise (webpack-internal:///../../../../zone.js/dist/zone.js:475:31) [angular]
    at resolvePromise (webpack-internal:///../../../../zone.js/dist/zone.js:460:17) [angular]
    at eval (webpack-internal:///../../../../zone.js/dist/zone.js:509:17) [angular]
    at Object.onInvokeTask (webpack-internal:///../../../core/src/zone/ng_zone.js:266:37) [angular]
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:261:40) [angular]
    at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:151:47) [<root> => angular]
    at drainMicroTaskQueue (webpack-internal:///../../../../zone.js/dist/zone.js:405:35) [<root>]
    at <anonymous> [<root>]
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:233
Zone.runGuarded @ zone.js:129
_loop_1 @ zone.js:416
drainMicroTaskQueue @ zone.js:425
Promise resolved (async)
scheduleQueueDrain @ zone.js:378
scheduleMicroTask @ zone.js:386
ZoneDelegate.scheduleTask @ zone.js:245
Zone.scheduleMicroTask @ zone.js:165
scheduleResolveOrReject @ zone.js:507
resolvePromise @ zone.js:470
(anonymous) @ zone.js:449
webpackJsonpCallback @ inline.bundle.js:22
(anonymous) @ components.module.chunk.js:1
zone.js:392 Unhandled Promise rejection: Error in :0:0 caused by: crypto.createHmac is not a function ; Zone: angular ; Task: Promise.then ; Value: ViewWrappedError {_nativeError: Error: Error in :0:0 caused by: crypto.createHmac is not a function
    at ViewWrappedError.BaseErro…, originalError: TypeError: crypto.createHmac is not a function
    at Object.sign (webpack-internal:///../../../../j…, context: DebugContext} TypeError: crypto.createHmac is not a function
    at Object.sign (webpack-internal:///../../../../jwa/index.js:34:23)
    at Object.jwsSign [as sign] (webpack-internal:///../../../../jws/lib/sign-stream.js:23:24)
    at Object.module.exports [as sign] (webpack-internal:///../../../../jsonwebtoken/sign.js:186:16)
    at CheckIMEIStatusComponent.ngOnInit (webpack-internal:///../../../../../src/app/components/check-imei-status/check-imei-status.component.ts:26:25)
    at Wrapper_CheckIMEIStatusComponent.ngDoCheck (/ComponentsModule/CheckIMEIStatusComponent/wrapper.ngfactory.js:22:53)
    at CompiledTemplate.proxyViewClass.View_CheckIMEIStatusComponent_Host0.detectChangesInternal (/ComponentsModule/CheckIMEIStatusComponent/host.ngfactory.js:28:38)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (webpack-internal:///../../../core/src/linker/view.js:438:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (webpack-internal:///../../../core/src/linker/view.js:633:44)
    at ViewRef_.detectChanges (webpack-internal:///../../../core/src/linker/view_ref.js:175:20)
    at RouterOutlet.activate (webpack-internal:///../../../router/src/directives/router_outlet.js:160:42)
    at ActivateRoutes.placeComponentIntoOutlet (webpack-internal:///../../../router/src/router.js:1359:16)
    at ActivateRoutes.activateRoutes (webpack-internal:///../../../router/src/router.js:1326:26)
    at eval (webpack-internal:///../../../router/src/router.js:1262:58)
    at Array.forEach (<anonymous>)
    at ActivateRoutes.activateChildRoutes (webpack-internal:///../../../router/src/router.js:1262:29)
consoleError @ zone.js:392
_loop_1 @ zone.js:421
drainMicroTaskQueue @ zone.js:425
Promise resolved (async)
scheduleQueueDrain @ zone.js:378
scheduleMicroTask @ zone.js:386
ZoneDelegate.scheduleTask @ zone.js:245
Zone.scheduleMicroTask @ zone.js:165
scheduleResolveOrReject @ zone.js:507
resolvePromise @ zone.js:470
(anonymous) @ zone.js:449
webpackJsonpCallback @ inline.bundle.js:22
(anonymous) @ components.module.chunk.js:1
zone.js:394 Error: Uncaught (in promise): Error: Error in :0:0 caused by: crypto.createHmac is not a function
TypeError: crypto.createHmac is not a function
    at Object.sign (webpack-internal:///../../../../jwa/index.js:34:23)
    at Object.jwsSign [as sign] (webpack-internal:///../../../../jws/lib/sign-stream.js:23:24)
    at Object.module.exports [as sign] (webpack-internal:///../../../../jsonwebtoken/sign.js:186:16)
    at CheckIMEIStatusComponent.ngOnInit (webpack-internal:///../../../../../src/app/components/check-imei-status/check-imei-status.component.ts:26:25)
    at Wrapper_CheckIMEIStatusComponent.ngDoCheck (/ComponentsModule/CheckIMEIStatusComponent/wrapper.ngfactory.js:22:53)
    at CompiledTemplate.proxyViewClass.View_CheckIMEIStatusComponent_Host0.detectChangesInternal (/ComponentsModule/CheckIMEIStatusComponent/host.ngfactory.js:28:38)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (webpack-internal:///../../../core/src/linker/view.js:438:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (webpack-internal:///../../../core/src/linker/view.js:633:44)
    at ViewRef_.detectChanges (webpack-internal:///../../../core/src/linker/view_ref.js:175:20)
    at RouterOutlet.activate (webpack-internal:///../../../router/src/directives/router_outlet.js:160:42)
    at ActivateRoutes.placeComponentIntoOutlet (webpack-internal:///../../../router/src/router.js:1359:16)
    at ActivateRoutes.activateRoutes (webpack-internal:///../../../router/src/router.js:1326:26)
    at eval (webpack-internal:///../../../router/src/router.js:1262:58)
    at Array.forEach (<anonymous>)
    at ActivateRoutes.activateChildRoutes (webpack-internal:///../../../router/src/router.js:1262:29)
    at Object.sign (webpack-internal:///../../../../jwa/index.js:34:23)
    at Object.jwsSign [as sign] (webpack-internal:///../../../../jws/lib/sign-stream.js:23:24)
    at Object.module.exports [as sign] (webpack-internal:///../../../../jsonwebtoken/sign.js:186:16)
    at CheckIMEIStatusComponent.ngOnInit (webpack-internal:///../../../../../src/app/components/check-imei-status/check-imei-status.component.ts:26:25)
    at Wrapper_CheckIMEIStatusComponent.ngDoCheck (/ComponentsModule/CheckIMEIStatusComponent/wrapper.ngfactory.js:22:53)
    at CompiledTemplate.proxyViewClass.View_CheckIMEIStatusComponent_Host0.detectChangesInternal (/ComponentsModule/CheckIMEIStatusComponent/host.ngfactory.js:28:38)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (webpack-internal:///../../../core/src/linker/view.js:438:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (webpack-internal:///../../../core/src/linker/view.js:633:44)
    at ViewRef_.detectChanges (webpack-internal:///../../../core/src/linker/view_ref.js:175:20)
    at RouterOutlet.activate (webpack-internal:///../../../router/src/directives/router_outlet.js:160:42)
    at ActivateRoutes.placeComponentIntoOutlet (webpack-internal:///../../../router/src/router.js:1359:16)
    at ActivateRoutes.activateRoutes (webpack-internal:///../../../router/src/router.js:1326:26)
    at eval (webpack-internal:///../../../router/src/router.js:1262:58)
    at Array.forEach (<anonymous>)
    at ActivateRoutes.activateChildRoutes (webpack-internal:///../../../router/src/router.js:1262:29)
    at resolvePromise (webpack-internal:///../../../../zone.js/dist/zone.js:475:31) [angular]
    at resolvePromise (webpack-internal:///../../../../zone.js/dist/zone.js:460:17) [angular]
    at eval (webpack-internal:///../../../../zone.js/dist/zone.js:509:17) [angular]
    at Object.onInvokeTask (webpack-internal:///../../../core/src/zone/ng_zone.js:266:37) [angular]
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:261:40) [angular]
    at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:151:47) [<root> => angular]
    at drainMicroTaskQueue (webpack-internal:///../../../../zone.js/dist/zone.js:405:35) [<root>]
    at <anonymous> [<root>]
```

**Angular version**

```
Angular CLI: 1.6.1
Node: 6.12.0
OS: linux x64
Angular: 2.4.9
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, upgrade

@angular/cli: 1.6.1
@angular/router: 3.4.9
@angular/tsc-wrapped: 0.5.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.2.1
webpack: 3.10.0
```

**Comment by joovel** [comment]
This library is not for the browser, and its dependent libraries require the `crypto` library that's built into node. You will probably need a different library that does not have that dependency.

**Comment by rajnishcoder** [comment]
@joovel thanks for the reply.
