### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by alee046** [auth0/node-jsonwebtoken#489]
I am getting a strange error, the below implementation works locally but it is throwing an error of undefined is not a function after it is being deployed on jenkins/aws.

`               
var accessToken = jwt.sign({user: credentials.name}, config.sessionSecretKey,{
                        expiresIn: 60 * 60
                    });
`

`
TypeError: undefined is not a function
    at Object.module.exports [as sign] (/node_modules/jsonwebtoken/sign.js:87:23)
    at  /controllers/Login.js:27:43
`

**Comment by alee046** [comment]
@JacoKoster Thank you for the response. We are using Node version 6.9 on our servers and it does run an npm install on jenkins. 

Was able to troubleshoot the issue but its sort of weird... I initially updated to the latest version (8.3) when I started getting that error. What we ended up doing was we copied a jsonwebtoken module from another project that was working properly. This module had a dependency of something called xxtend (sp), so im not entirely sure what it could be. It seems to be a misnaming of version or module names. There might be 2 different 'jsonwebtoken' packages it seems.
