### ISSUE TITLE
Exception thrown when used with node v0.10.32 whereas working fine with node v0.10.18

### ISSUE THREAD

**Issue by narendrasoni1989** [auth0/node-jsonwebtoken#58]
This is how i am using it:
var token = require("jsonwebtoken").sign({name:"some name",email:"some email"}, 'hello-private-key', { algorithm: 'RS256'});

Same implementation is working in v0.10.18 whereas in my other machine where i am running v0.10.32, it is not working.

Below is the stack trace: 
140735299650320:error:0906D06C:PEM routines:PEM_read_bio:no start line:../deps/openssl/openssl/crypto/pem/pem_lib.c:703:Expecting: ANY PRIVATE KEY

/Users/narendra/Documents/workspace/NodeJsWorkspace/mean-jwt-auth/node_modules/mongoose/node_modules/mpromise/lib/promise.js:108
  if (this.ended && !this.hasRejectListeners()) throw reason;
                                                      ^
Error: SignFinal error
    at Sign.sign (crypto.js:398:27)
    at Object.sign (/Users/narendra/Documents/workspace/NodeJsWorkspace/mean-jwt-auth/node_modules/jsonwebtoken/node_modules/jws/node_modules/jwa/index.js:52:47)
    at Object.jwsSign [as sign] (/Users/narendra/Documents/workspace/NodeJsWorkspace/mean-jwt-auth/node_modules/jsonwebtoken/node_modules/jws/index.js:34:26)
    at Object.module.exports.sign (/Users/narendra/Documents/workspace/NodeJsWorkspace/mean-jwt-auth/node_modules/jsonwebtoken/index.js:46:20)

**Comment by woloski** [comment]
you have to send a PEM encoded certificate as the private key if you use rs256






On Sun, Mar 1, 2015 at 7:17 PM -0800, "Narendra Kumar Soni" <notifications@github.com> wrote:












This is how i am using it:

var token = require("jsonwebtoken").sign({name:"some name",email:"some email"}, 'hello-private-key', { algorithm: 'RS256'});



Same implementation is working in v0.10.18 whereas in my other machine where i am running v0.10.32, it is not working.



Below is the stack trace: 

140735299650320:error:0906D06C:PEM routines:PEM_read_bio:no start line:../deps/openssl/openssl/crypto/pem/pem_lib.c:703:Expecting: ANY PRIVATE KEY



/Users/narendra/Documents/workspace/NodeJsWorkspace/mean-jwt-auth/node_modules/mongoose/node_modules/mpromise/lib/promise.js:108

  if (this.ended && !this.hasRejectListeners()) throw reason;

                                                      ^

Error: SignFinal error

    at Sign.sign (crypto.js:398:27)

    at Object.sign (/Users/narendra/Documents/workspace/NodeJsWorkspace/mean-jwt-auth/node_modules/jsonwebtoken/node_modules/jws/node_modules/jwa/index.js:52:47)

    at Object.jwsSign as sign

    at Object.module.exports.sign (/Users/narendra/Documents/workspace/NodeJsWorkspace/mean-jwt-auth/node_modules/jsonwebtoken/index.js:46:20)
