### ISSUE TITLE
Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag

### ISSUE THREAD

**Issue by asinner** [auth0/node-jsonwebtoken#630]
I'm using this package (`v8.5.1`) to verify a token. The token was signed using the RS256 algorithm. Using jwt.io I was able to verify the signature using the public key I was given.   (shareable link [here](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE1NjY4NTU2MTksImlhdCI6MTU2Njg1MjAxOSwiaXNzIjoiaXBjdCIsInB1aWQiOiJhc2lubmVyIn0.xeaEan7DoDe-awTJVivGIF-8QBwVkBmOkLiF_eBrHOpWTeUXUbVDo3-0v7e0vHMUXskStarlRwo-0lTez0lhHJTsvi6ITnKfrpeayI-mVmydrIcs09CsmOPGtLR0poNiSpFOpzz1Mi8y7DDtxhsIReOsw9E5NNZPeSrxei0DDE8&publicKey=-----BEGIN%20RSA%20PUBLIC%20KEY-----%0AMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDTYD0P%2BHpADJ9w3W0zqZYpJNqK%0AeMfuaUx%2FdsZ49VugtuV%2Fi3iCk7LC0lcBoupTE57uNuzZbU5E8mZxswJqgCQ%2BXnS8%0ArGQll9LKp%2Bqx%2FDnupKsQdgbTL9QDrGbyK5W8QiLFLHzbLMEnGx%2BBcPOssltyMOA6%0AZJxOyUMlv8VGUlWQywIDAQAB%0A-----END%20RSA%20PUBLIC%20KEY-----%0A))

However, when verifying the token in my code (Node v10.15.3) I'm receiving the following error:

```
Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
    at Verify.verify (internal/crypto/sig.js:119:23)
    at Object.verify (/<path>/node_modules/jwa/index.js:164:21)
    at Object.jwsVerify [as verify] (/<path>/node_modules/jws/lib/verify-stream.js:54:15)
    at /<path>/node_modules/jsonwebtoken/verify.js:127:19
    at getSecret (/<path>/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/<path>/node_modules/jsonwebtoken/verify.js:94:10)
    at getPublicKey.then.publicKey (/<path>/test-jwt.js:20:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11
```

The code I'm using is this:

```js
const pubKey = fs.readFileSync('./public-key-file').toString()

jwt.verify(token, pubKey, (err, payload) => {
  console.error(err)
})
```

public key used to verify the token:

```
-----BEGIN RSA PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDTYD0P+HpADJ9w3W0zqZYpJNqK
eMfuaUx/dsZ49VugtuV/i3iCk7LC0lcBoupTE57uNuzZbU5E8mZxswJqgCQ+XnS8
rGQll9LKp+qx/DnupKsQdgbTL9QDrGbyK5W8QiLFLHzbLMEnGx+BcPOssltyMOA6
ZJxOyUMlv8VGUlWQywIDAQAB
-----END RSA PUBLIC KEY-----
```

**Comment by panva** [comment]
Hi @asinner,

asn.1 parsers come in different flavors, some more forgiving than others, the one used by jwt.io uses a rather lax one. `jsonwebtoken` does not bundle one but instead relies on node's `crypto` module to parse key material.

I've ran the key through three different asn.1 implementations and it fails to be parsed in each one.

asn1.js definitions from [`@panva/jose`](https://github.com/panva/jose/blob/master/lib/help/asn1/index.js)
```js
{ Error: Failed to match tag: "int" at: ["n"]
    at DecoderBuffer.error (/Users/panva/repo/ultimate-jose/node_modules/asn1.js/lib/asn1/base/reporter.js:78:11)
    at DERNode.decodeTag [as _decodeTag] (/Users/panva/repo/ultimate-jose/node_modules/asn1.js/lib/asn1/decoders/der.js:71:19)
    at DERNode.decode [as _decode] (/Users/panva/repo/ultimate-jose/node_modules/asn1.js/lib/asn1/base/node.js:341:25)
    at decodeChildren (/Users/panva/repo/ultimate-jose/node_modules/asn1.js/lib/asn1/base/node.js:378:15)
    at Array.forEach (<anonymous>)
    at DERNode.decode [as _decode] (/Users/panva/repo/ultimate-jose/node_modules/asn1.js/lib/asn1/base/node.js:375:22)
    at DERNode.decode [as _decode] (/Users/panva/repo/ultimate-jose/node_modules/asn1.js/lib/asn1/base/node.js:280:47)
    at Generated.decode (/Users/panva/repo/ultimate-jose/node_modules/asn1.js/lib/asn1/decoders/der.js:28:20)
    at Generated.decode (/Users/panva/repo/ultimate-jose/node_modules/asn1.js/lib/asn1/decoders/pem.js:50:38)
    at Entity.decode (/Users/panva/repo/ultimate-jose/node_modules/asn1.js/lib/asn1/api.js:44:32)
  path: '["n"]',
  message: 'Failed to match tag: "int" at: ["n"]' }
```

OpenSSL (node 12)
```js
Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
    at createPublicKey (internal/crypto/keys.js:321:10)
    at Script.runInThisContext (vm.js:123:20)
    at REPLServer.defaultEval (repl.js:358:29)
    at bound (domain.js:415:14)
    at REPLServer.runBound [as eval] (domain.js:428:12)
    at REPLServer.onLine (repl.js:665:10)
    at REPLServer.emit (events.js:201:15)
    at REPLServer.EventEmitter.emit (domain.js:471:20) {
  opensslErrorStack: [
    'error:0D09B00D:asn1 encoding routines:d2i_PublicKey:ASN1 lib',
    'error:0D08303A:asn1 encoding ' +
      'routines:asn1_template_noexp_d2i:nested ' +
      'asn1 error',
    'error:0D06C03A:asn1 encoding ' +
      'routines:asn1_d2i_ex_primitive:nested ' +
      'asn1 error'
  ],
  library: 'asn1 encoding routines',
  function: 'asn1_check_tlen',
  reason: 'wrong tag',
  code: 'ERR_OSSL_ASN1_WRONG_TAG'
}
```

BoringSSL (node 12 but electron runtime)
```
Error: error:03000075:bignum routines:OPENSSL_internal:BAD_ENCODING
    at createPublicKey (internal/crypto/keys.js:321:10)
    at Script.runInContext (vm.js:134:20)
    at REPLServer.defaultEval (repl.js:386:29)
    at bound (domain.js:415:14)
    at REPLServer.runBound [as eval] (domain.js:428:12)
    at REPLServer.onLine (repl.js:700:10)
    at REPLServer.emit (events.js:200:13)
    at REPLServer.EventEmitter.emit (domain.js:471:20) {
  opensslErrorStack: [ 'error:04000064:RSA routines:OPENSSL_internal:BAD_ENCODING' ],
  library: 'bignum routines',
  function: 'OPENSSL_internal',
  reason: 'BAD_ENCODING',
  code: 'ERR_OSSL_BN_BAD_ENCODING'
}
```

It is fair to say the key is not properly encoded.

**Comment by rramk** [comment]
Hi @panva , i'm encountering the same error. Can you shed some light on how to verify the public key directly with asn1 ? Some example code would be of great help!

**Comment by panva** [comment]
I'm using https://lapo.it/asn1js to view the PEM structure.

E.g.
- valid public pkcs1 key [link](https://lapo.it/asn1js/#MIGJAoGBAOHPF4yUXW3lOSZwYSXF8wSq6ZwhSTHnysP_ds1nTzpoxwvPUWVDdxbVN6D7HGfhkg4dVchS7wJ3QTn-fFmW88zYtpdnRS9550Ywi1hr0l0Xz3A1mm44mWOyJ-moAug9Sw2zxJA2WY8zudZjIMmbD-KII5SNuM7SAtdE7__0raWfAgMBAAE)
- the one from the comment above [link](https://lapo.it/asn1js/#MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDTYD0P-HpADJ9w3W0zqZYpJNqKeMfuaUx_dsZ49VugtuV_i3iCk7LC0lcBoupTE57uNuzZbU5E8mZxswJqgCQ-XnS8rGQll9LKp-qx_DnupKsQdgbTL9QDrGbyK5W8QiLFLHzbLMEnGx-BcPOssltyMOA6ZJxOyUMlv8VGUlWQywIDAQAB)

You can clearly see something's not right.

As far as running the key through a parser,

starting with Node 12 use the [crypto KeyObject API](https://nodejs.org/docs/latest-v12.x/api/crypto.html#crypto_class_keyobject), this will either give you a KeyObject instance back or throw when the key material isn't properly formatted. This will give you OpenSSL asn1 parser check.

```
crypto.createPublicKey(pem)
crypto.createPrivateKey(pem)
```

Starting with `electron` v6.0.0 you can also do the same in electron REPL (`npx electron@6.0.0 -i`), this will give you BoringSSL asn1 parser check.

**Comment by komanton** [comment]
You just need to remove the word 'RSA' from the header and footer.

**Comment by wjndy4** [comment]
> You just need to remove the word 'RSA' from the header and footer.
thank you very much

**Comment by wjndy4** [comment]
> You just need to remove the word 'RSA' from the header and footer.

thank you very much

**Comment by Revilotom** [comment]
@komanton @wjndy4 Do you know why it works when `RSA` is removed?

**Comment by komanton** [comment]
@Revilotom Sorry, I can't remember, actually 😞 I played a lot with ASN.1 decoders somehow and after some debugging came to this idea.

**Comment by Muhammad-Tayyab67** [comment]
@wjndy4 I am still facing the same error after removing the RSA

**Comment by oggy107** [comment]
> You just need to remove the word 'RSA' from the header and footer.

Thanks dude
