### ISSUE TITLE
Invalid Signature when running jwt.verify with the token and local pem file.

### ISSUE THREAD

**Issue by ankur2311** [auth0/node-jsonwebtoken#670]
Hi Team,

We faced an issue in our azure application where we are trying to verify the JWT token received from login.microsoftonline.com/* api, against a locally stored pem file.
Following is the code we use to verify:

`const authToken = req.headers.authorization;`
`const token = authToken.split(" ")[1];`
`var cert = fs.readFileSync('./appointments-fed.pem');`
`let decoded = await jwt.verify(token,cert, {algorithms: ['RS256']});`

The verification worked for many days on lower environments as well as production for couple days, before we started seeing the following exception in console logs:

`JsonWebTokenError: invalid signature
    at D:\home\site\wwwroot\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (D:\home\site\wwwroot\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\home\site\wwwroot\node_modules\jsonwebtoken\verify.js:94:10)
   at checkToken (D:\home\site\wwwroot\wedding-appointments\config\middleware.js:18:37)
    at Layer.handle [as handle_request] (D:\home\site\wwwroot\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:317:13)
    at D:\home\site\wwwroot\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:335:12)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:275:10)
    at D:\home\site\wwwroot\app.js:68:9
    at Layer.handle [as handle_request] (D:\home\site\wwwroot\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:317:13)
    at D:\home\site\wwwroot\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:335:12)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\index.js:275:10)
    at D:\home\site\wwwroot\node_modules\body-parser\lib\read.js:130:5
    at invokeCallback (D:\home\site\wwwroot\node_modules\raw-body\index.js:224:16)
    at done (D:\home\site\wwwroot\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (D:\home\site\wwwroot\node_modules\raw-body\index.js:273:7)
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
`

Now we don't own the token generation part and we directly pass the token received from the microsoft api to our backend API to verify and pass through.

To resolve the issue, we had a new pem file created through `jwt.io`  from the new token. 
After we replaced the new pem file in our codebase the exception was gone and verification was successful. However, even when we replaced the new pem file with the old one (for which we saw exceptions), it still is working fine in all the environments.

Since the issue got resolved after we created a new pem file, we are trying to get a root cause for this, so we could prevent this from happening again.

Any pointers are much appreciated. 

Thanks,
Ankur

**Comment by panva** [comment]
@ankur2311 are you aware that microsoft is rotating their signing keys regularly?

**Comment by ankur2311** [comment]
Thanks @panva for the pointer.
We raised a ticket with MS and found out it was indeed the cause of the problem.
Thanks much.
