### ISSUE TITLE
Unknown application error occurred

### ISSUE THREAD

**Issue by c316** [auth0/node-jsonwebtoken#774]
### Description

I have been working with Vercel support to resolve an issue where the jsonwebtoken package is encountering an error, "Unknown application error occurred". Vercel has directed me to open an issue here. 

### Reproduction
https://github.com/vercel-support/issue-reproduction

Here are my steps. 

1. Clone the repo https://github.com/vercel-support/issue-reproduction
2. run, "yarn"
3. run the code in the api/login/checksecurityans file
4. Open Postman and POST to localhost:3000/api/login/checksecurityans
5. Get this error if you ran the code using 'vercel dev'

```
Cannot find module 'jsonwebtoken'
Require stack:
- /Users/josh.bechard/Dev/issue-reproduction/api/services/jwt-token-service.js
- /Users/josh.bechard/Dev/issue-reproduction/api/login/checksecurityans.js
- /Users/josh.bechard/.nvm/versions/node/v14.15.4/lib/node_modules/vercel/node_modules/@vercel/node/dist/launcher.js
- /Users/josh.bechard/.nvm/versions/node/v14.15.4/lib/node_modules/vercel/node_modules/@vercel/node/dist/dev-server.js
Did you forget to add it to "dependencies" in `package.json`?
Error! `node api/login/checksecurityans.js` failed with exit code 1
```

Or if you ran the file using node you might see an error like this one
```
[POST] /api/login/checksecurityans
17:08:28:62
2021-03-22T22:08:28.686Z    6d89535a-42b6-4836-89cd-1de6611f75ea    ERROR    Unhandled Promise Rejection  {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: error:0909006C:PEM routines:get_name:no start line","reason":{"errorType":"Error","errorMessage":"error:0909006C:PEM routines:get_name:no start line","code":"ERR_OSSL_PEM_NO_START_LINE","library":"PEM routines","function":"get_name","reason":"no start line","stack":["Error: error:0909006C:PEM routines:get_name:no start line","    at Sign.sign (internal/crypto/sig.js:110:29)","    at Object.sign (/var/task/api/node_modules/jwa/index.js:152:45)","    at Object.jwsSign [as sign] (/var/task/api/node_modules/jws/lib/sign-stream.js:32:24)","    at Object.module.exports [as sign] (/var/task/api/node_modules/jsonwebtoken/sign.js:204:16)","    at JwtTokenService.generateJwt (/var/task/api/services/jwt-token-service.js:57:29)","    at checkSecurityAns (/var/task/api/login/checksecurityans.js:4:33)","    at Server.<anonymous> (/var/task/___vc_helpers.js:813:19)","    at Server.emit (events.js:315:20)","    at parserOnIncoming (_http_server.js:874:12)","    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: error:0909006C:PEM routines:get_name:no start line","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at process.emit (/var/task/___vc_sourcemap_support.js:587:21)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:94:32)"]}
Unknown application error occurred

```

I do have a package.json file and it does include jsonwebtoken. 

### Environment

"jsonwebtoken": "8.5.1"
Node v14

**Comment by rkaw92** [comment]
1. I'm not sure exactly how Vercel runs the application, but my guess is it never finds `package.json` because it's in a subdirectory, so it never installs dependencies.
2. RSA requires private and public key files in a particular format (PEM) - you can't just pass some strings and expect them to work. Generate test keys using OpenSSL.
