### ISSUE TITLE
Malformed token error with base64 encoded secret

### ISSUE THREAD

**Issue by revjtanton** [auth0/node-jsonwebtoken#783]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Using a `base64` encoded secret with an HS256 token generates a `Malformed token` error. A full output of the error is as follows:
```
app_1  | Error: Malformed token
app_1  |     at /usr/src/app/.build/src/auth/authController.js:54:27
app_1  |     at step (/usr/src/app/.build/src/auth/authController.js:33:23)
app_1  |     at Object.next (/usr/src/app/.build/src/auth/authController.js:14:53)
app_1  |     at /usr/src/app/.build/src/auth/authController.js:8:71
app_1  |     at new Promise (<anonymous>)
app_1  |     at __awaiter (/usr/src/app/.build/src/auth/authController.js:4:12)
app_1  |     at exports.handler (/usr/src/app/.build/src/auth/authController.js:47:45)
app_1  |     at InProcessRunner.run (/usr/src/app/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:190:16)
app_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
app_1  |     at async LambdaFunction.runHandler (/usr/src/app/node_modules/serverless-offline/dist/lambda/LambdaFunction.js:355:20)
app_1  |     at async Object.authenticate (/usr/src/app/node_modules/serverless-offline/dist/events/http/createAuthScheme.js:101:24)
app_1  |     at async module.exports.internals.Manager.execute (/usr/src/app/node_modules/@hapi/hapi/lib/toolkit.js:45:28)
app_1  |     at async module.exports.internals.Auth._authenticate (/usr/src/app/node_modules/@hapi/hapi/lib/auth.js:256:30)
app_1  |     at async Request._lifecycle (/usr/src/app/node_modules/@hapi/hapi/lib/request.js:312:32)
app_1  |     at async Request._execute (/usr/src/app/node_modules/@hapi/hapi/lib/request.js:221:9)
app_1  | offline: Authorization function returned an error response: (λ: auth)
```

### Reproduction

1. Generate a token and key from here: https://java.jsonwebtoken.io/ or https://jwt.io and set the secret to base64 encoded
2. Add the secret key to your project.
3. Pass a request with the generated JWT and watch it error out. Code as follows:
```
      const valid = jwt.verify(
        token,
        Buffer.from(process.env.JWT_KEY, 'base64'),
        { algorithms: ['HS256'] }
      )
``` 

### Environment

> Please provide the following:

- **Version of this library used: 8.5.1
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser): I'm using serverless-offline. This is a Lambda-based API
- **Other modules/plugins/libraries that might be involved: While I was able to re-create this using both java.jsonwebtoken.io and jwt.io I was also able to recreate the issue using tokens and keys directly using JJWT in Springboot. Note: the generated secret and token _does_ work from any of these sources when using it within the Springboot API. Also of note is that this is all running in Docker. Also of note if I generate a token from jwt.io w/out base64 encoding the key then this will work fine (w/out `Buffer` obviously).

**Comment by revjtanton** [comment]
I guess nobody else is having this issue? I have been unable to find any workaround.

**Comment by Jeff-Tian** [comment]
Met the same issue with HS256, without **'base64'**. But it only occurs sometimes, not always. :-(

**Comment by KevsRepos** [comment]
Got the same issue. This is driving me crazy.

**Comment by Amer-Jabar** [comment]
I generated the token with Spring Boots jws library and verified it with jsonwebtoken in a nodejs server without any issues. If you try to verify it without setting to base64 it will not verify the token (at least for when signing it with base64 as in my case).

**Comment by toymachiner62** [comment]
Shouldn't `Buffer.from(process.env.JWT_KEY, 'base64'),` actually be `Buffer.from(process.env.JWT_KEY).toString('base64')`?

**Comment by BigBrainAFK** [comment]
I actually encountered malformed token issues as well. Its just sometimes but its caused by the token having `..` at some points instead of just `.` .

If I manually remove one of the `.` from `..` the token still can be verified and is valid but the malform error doesnt show up.

EDIT: The tokens I was trying to decode were also encoded by this library so its extra weird that this can happen.
