### ISSUE TITLE
jwt.verify Error: PEM_read_bio_PUBKEY failed

### ISSUE THREAD

**Issue by scolobey** [auth0/node-jsonwebtoken#791]
### Description

I recently started getting errors on jwt.verify

```
jwt.verify(token, publicKey, function(err, decoded) {
      if (err) {
        reject(err)
      }
      else {
        resolve(decoded)
      }
    });
```

But if I take the token and the publicKey and plug it in [here](https://jwt.io/) the token validates.

Here's the error:

```
(node:25269) UnhandledPromiseRejectionWarning: Error: PEM_read_bio_PUBKEY failed
    at Verify.verify (internal/crypto/sig.js:119:23)
    at Object.verify (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/jwa/index.js:164:21)
    at Object.jwsVerify [as verify] (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/jws/lib/verify-stream.js:54:15)
    at /Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/jsonwebtoken/verify.js:127:19
    at getSecret (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/jsonwebtoken/verify.js:94:10)
    at /Users/Ryan/Desktop/Projects/javascript/funky-radish-api/app/services/token_service.js:59:9
    at new Promise (<anonymous>)
    at Object.exports.verifyToken (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/app/services/token_service.js:58:34)
    at exports.verify (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/app/controllers/auth.controller.js:250:18)
    at Layer.handle [as handle_request] (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/express/lib/router/index.js:281:22
    at param (/Users/Ryan/Desktop/Projects/javascript/funky-radish-api/node_modules/express/lib/router/index.js:354:14)
```

### Repro

Here's the public key I'm using for testing:

```
-----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2hCERBhkZ9A0z7l+vPQv
  zsaHX0qEIWl+1wYeM04ZllS5CHneRwK2/fjwmp51ChGOPOGuK3nxLGaHqkCEzmxT
  1KuNF3r1DiYTERKJzPZJADD2TNKWELQkOA7YRxAfEDUM8dq3g2iOK8BJ93MXePzV
  l/mbbeGm+3F/pukxsBHxgReS3rO2oBLvyihY+jvT8+AaynNOLin24os8/7gNZZyU
  xy04/xIQf5H9+v1ifzFfa2Ee182itXxnoNjtGnMdv0wcByejcNODr7WyruM/1+Ee
  SCw1VA/dh8FapXur9E02luliDac7OEgm9Tmbanux3wQeafejAuTgWJXZoDSbfCV7
  NwIDAQAB
  -----END PUBLIC KEY-----
```

And here's a generated token that results in an error:

`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsInVzZXIiOiI2MTQwYTY1YjY1NWNhYTVkY2ExOTQ3NzgiLCJzdWIiOiI2MTQwYTY1YjY1NWNhYTVkY2ExOTQ3NzgiLCJhdWQiOiJmdW5reS1yYWRpc2gtdHdkeHYiLCJpYXQiOjE2MzE2MjY4NDMsImV4cCI6MTYzMTcxMzI0M30.Rz3eolKmUtzmaAklyopYoje72dYYhAYyzkdLzPgqhoXzrh5vuQLjcLsPLSq9tOdKS7FK6eual3IvMI2Hh-NkSqhdZ66R-dFJ3Xo00YyMfGvrw_Pd63SY33bx8M0XjM-Guz53e0LqqDNd4z7-75YK6nS6gXIrtGLo055R8zZKTXAQkUMhH61ZarAaG00q6ZMQMzrvkkYt-PNGDIgxExemnHtivdZ2RAM4Q8EcpCjc32S9BhuwDad6o0nj68gw7PTJ56z6BQ30CYav92YcAWazH_u36Z9SJIpS3qXmFA9Awmjo8YEkhup8gMij7Svit6duzVx7QNVUHYLKF_RODyYAEQ`

### Environment

jsonwebtoken: 8.5.1
Node: v10.20.1

**Comment by scolobey** [comment]
I did resolve this after refreshing all of my keys.
Definitely my own mistake somewhere, but I have no idea where.
