### ISSUE TITLE
Can't create npm shrinkwrap with express-jwt in package.json

### ISSUE THREAD

**Issue by paambaati** [auth0/node-jsonwebtoken#80]
I have a project where I use both node-jsonwebtoken and express-jwt. After the upgrade to node-jsonwebtoken `5.0.0`, I can't create a npm shrinkwrap, as express-jwt, I believe, depends on `4.x`. Here's the npm debug log.

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'shrinkwrap' ]
2 info using npm@2.7.6
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 warn unmet dependency /Users/gp/Projects/myproject/node_modules/express-jwt requires jsonwebtoken@'~4.2.0' but will load
5 warn unmet dependency /Users/gp/Projects/myproject/node_modules/jsonwebtoken,
5 warn unmet dependency which is version 5.0.0
6 verbose stack Error: Problems were encountered
6 verbose stack Please correct and try again.
6 verbose stack invalid: jsonwebtoken@5.0.0 /Users/gp/Projects/myproject/node_modules/jsonwebtoken
6 verbose stack     at shrinkwrap_ (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:37:15)
6 verbose stack     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:31:5
6 verbose stack     at /usr/local/lib/node_modules/npm/lib/ls.js:47:30
6 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
6 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
6 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
6 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
6 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
6 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
6 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
7 verbose cwd /Users/gp/Projects/myproject
8 error Darwin 14.3.0
9 error argv "node" "/usr/local/bin/npm" "shrinkwrap"
10 error node v0.12.2
11 error npm  v2.7.6
12 error Problems were encountered
12 error Please correct and try again.
12 error invalid: jsonwebtoken@5.0.0 /Users/gp/Projects/myproject/node_modules/jsonwebtoken
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]
 ```

**Comment by pose** [comment]
@paambaati We have released `express-jwt@3.0.0` that fixes this issue by updating dependency to `jsonwebtoken@5.0.0`. Feel free to reopen if you still experiencing this issue. Thanks!
