### ISSUE TITLE
DSO support routines:dlfcn_load:could not load the shared library

### ISSUE THREAD

**Issue by matheuscamarques** [auth0/node-jsonwebtoken#831]
Error: error:25066067:DSO support routines:dlfcn_load:could not load the shared library
    at Sign.sign (internal/crypto/sig.js:110:29)
    at Object.sign (/home/sanonichan/projetos/botpag/py-jwt-test/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/home/sanonichan/projetos/botpag/py-jwt-test/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.module.exports [as sign] (/home/sanonichan/projetos/botpag/py-jwt-test/node_modules/jsonwebtoken/sign.js:204:16)
    at Object.checkAcess3 (/home/sanonichan/projetos/botpag/py-jwt-test/parcelamento.module.js:156:37)
    at async /home/sanonichan/projetos/botpag/py-jwt-test/parcelamento.module.js:200:5 {
  opensslErrorStack: [
    'error:0E076071:configuration file routines:module_run:unknown module name',
    'error:0E07506E:configuration file routines:module_load_dso:error loading dso',
    'error:25070067:DSO support routines:DSO_load:could not load the shared library'
  ],
  library: 'DSO support routines',
  function: 'dlfcn_load',
  reason: 'could not load the shared library',
  code: 'ERR_OSSL_DSO_COULD_NOT_LOAD_THE_SHARED_LIBRARY'
}

**Comment by Eleftheria-99** [comment]
Heyy , I am facing the same issue , any progress on finding a solution ? or what is causing this ?

**Comment by Sheile** [comment]
FYI, I've faced same issue and found following mitigate method.

This error will be occurred when call `jsonwebtoken.sign` first time in process.
Second call does not occur this error.

therefore, You can call this method with dummy parameter and ignore exception at the first of program for mitigation.

```
try {
  jsonwebtoken.sign(dummyPayload, PRIVATE_KEY, jwtOptions)
} catch(e) {
}
```

**Comment by jacobg** [comment]
I also just encountered this issue on GKE. The VM is running COS version 93 (https://cloud.google.com/container-optimized-os/docs/release-notes/m93). It also strangely only fails the first time, and succeeds the second time. I discovered that, because via retry logic wrapping the google-auth-library call.

There have been other reports of this error on Ubuntu 22.04:
https://github.com/firebase/firebase-admin-node/issues/1712
https://stackoverflow.com/questions/72104449/node-js-crypto-fails-to-sign-pem-key-string-from-file-with-error25066067dso-su

As noted there, another workaround suggested is to set the environment variable `OPENSSL_CONF=/dev/null`. I'm not sure what approach to take here.

**Comment by nayruthCalla** [comment]
Hello everyone, I also had the same problem but [here](https://github.com/nodejs/node/discussions/43184) is a discussion about this error, and the solution that has helped me is to change the node version from v16.15.1 to v16.16.0, I hope it helps. 
P.S.: I also have Ubuntu 22.04

**Comment by christophe-g** [comment]
Hitting this as well on a fresh install of Linux Mint 21 / cinnamon. 
Workaround described here https://github.com/firebase/firebase-admin-node/issues/1712 solved it.
