### ISSUE TITLE
Does jsonwebtoken support use in browsers?

### ISSUE THREAD

**Issue by ajmas** [auth0/node-jsonwebtoken#845]
I am inheriting the development of an exist Quasar based project (Vue framework) and I am getting the following eror:

```
data-stream.js:39 Uncaught TypeError: util.inherits is not a function
    at node_modules/jws/lib/data-stream.js (data-stream.js:39:6)
    at __require (chunk-OL3AADLO.js?v=0d8bb0a7:9:50)
    at node_modules/jws/lib/sign-stream.js (sign-stream.js:3:18)
    at __require (chunk-OL3AADLO.js?v=0d8bb0a7:9:50)
    at node_modules/jws/index.js (index.js:2:18)
    at __require (chunk-OL3AADLO.js?v=0d8bb0a7:9:50)
    at node_modules/jsonwebtoken/decode.js (decode.js:1:11)
    at __require (chunk-OL3AADLO.js?v=0d8bb0a7:9:50)
    at node_modules/jsonwebtoken/index.js (index.js:2:11)
    at __require (chunk-OL3AADLO.js?v=0d8bb0a7:9:50)
```

Looking at the `jws` it seems very targeted towards the server side, due to certain node.js dependencies. I am wondering whether in turn this makes `jsonwebtoken` node.js specific and not suitable for use in a browser?

If `jsonwebtoken` should work in a browser are there any specifics we should take into account? I am not seeing anything in the documentation.

**Comment by panva** [comment]
The `jsonwebtoken` library is only made for the Node.js runtime. For Browser or other Web-interoperable runtimes (e.g. Deno, Cloudlare Workers, ...) please see https://jwt.io/libraries?language=JavaScript.
