### ISSUE TITLE
can't verify token. it will show 500 error code.

### ISSUE THREAD

**Issue by tytom2003** [auth0/node-jsonwebtoken#853]
### Description

my code:
jwt.verify(token, 'Refresh_Access_Secret');

i verify token. it show below error.

GET /api/user/refreshtoken 500 7.732 ms - 1021
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.writeHead (node:_http_server:275:11)
    at ServerResponse.writeHead (D:\reactjs\mysql\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:266:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\reactjs\mysql\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (D:\reactjs\mysql\node_modules\express\lib\response.js:267:15)
    at eval (webpack://mysql/./src/config/express.js?:80:26)
    at Layer.handle_error (D:\reactjs\mysql\node_modules\express\lib\router\layer.js:71:5)

### Reproduction

when i verify token ' jwt.verify(token, 'Refresh_Access_Secret');'

> Where applicable, please include:

program run the below code. it will show 'RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined';
jwt.verify(token, 'Refresh_Access_Secret');

### Environment

> Please provide the following:

OS: windows 10
"jsonwebtoken": "^8.5.1",

**Comment by cwdabba** [comment]
Same here even I get this error **Invalid Token** error. Really frustrating. Spent my 3 hours of time.

OS: Mac
Package Version: **^8.5.1**

**Comment by cwdabba** [comment]
Found temporary solution. Not sure if this is how it should work

**Problem**
While sending API request in Postman I was sending it as **Authorization -> Bearer Token**

**Solution**
`Authorization -> API Key -> Key: Authorization       Value: TOKEN`

And then it started working

**Comment by tytom2003** [comment]
> Found temporary solution. Not sure if this is how it should work
> 
> **Problem** While sending API request in Postman I was sending it as **Authorization -> Bearer Token**
> 
> **Solution** `Authorization -> API Key -> Key: Authorization Value: TOKEN`
> 
> And then it started working

I tried using postman to verify token. It is not work. i don't know what happen. I suspect jsonwebtoken package problem. Since, i try to use njwt package to verify token. njwt package is OK.
