### ISSUE TITLE
Unable to resolve module crypto in Node backend

### ISSUE THREAD

**Issue by melissa07** [auth0/node-jsonwebtoken#899]
### Description

I'm trying to use the sign function in my NodeJS backend of my React Native application.

### Reproduction

 I have the following code:
![image](https://user-images.githubusercontent.com/14019994/229257892-34048459-0e8b-4908-9e59-e8d65c1b7d74.png)

and it's throwing me the following error:
`Error: Unable to resolve module crypto from /Users/{username}/Documents/Projets/app/server/node_modules/jsonwebtoken/verify.js: crypto could not be found within the project or in these directories:
  server/node_modules/jsonwebtoken/node_modules
  server/node_modules
  node_modules
   7 | const PS_SUPPORTED = require('./lib/psSupported');
   8 | const jws = require('jws');
>  9 | const {KeyObject, createSecretKey, createPublicKey} = require("crypto");
     |                                                                ^
  10 |
  11 | const PUB_KEY_ALGS = ['RS256', 'RS384', 'RS512'];
  12 | const EC_KEY_ALGS = ['ES256', 'ES384', 'ES512'];
    at ModuleResolver.resolveDependency (/Users/{username}/Documents/Projets/app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
    at DependencyGraph.resolveDependency (/Users/{username}/Documents/Projets/app/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/{username}/Documents/Projets/app/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/{username}/Documents/Projets/app/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/{username}/Documents/Projets/app/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Graph._addDependency (/Users/{username}/Documents/Projets/app/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 0)
    at async Graph._processModule (/Users/{username}/Documents/Projets/app/node_modules/metro/src/DeltaBundler/Graph.js:263:5)`

### Environment

> Please provide the following:
![image](https://user-images.githubusercontent.com/14019994/229257862-bdce2d08-233f-4beb-a2e9-cd56a476c704.png)

My version of Node is 16.15.1

**Comment by AStoker** [comment]
Issue exists in our project using Node 18 too.

**Comment by Anabil-Baruah** [comment]
Hi does this issue still exists ?

**Comment by mjk859** [comment]
issue still exists:
ERROR in ./node_modules/jsonwebtoken/sign.js 16:4-21
Module not found: Error: Can't resolve 'crypto' in 'D:\Xtra\TMS\frontend\node_modules\jsonwebtoken'

**Comment by AnasRezaMdlz** [comment]
Reason: Earlier Node modules used to support the polyfills which isn't the case now. Polyfills like crypto, stream and util are required for this package

Solution:
In my gatsby project, I did this and resolved
1) Installed crypto-browserify, stream-browserify and util
2) exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
   resolve: {
      fallback: {
        crypto: require.resolve('crypto-browserify'),
        stream: require.resolve("stream-browserify"),
        util: require.resolve("util/")
      },
    },
  })
}
