### ISSUE TITLE
TypeError: validator.isValid is not a function

### ISSUE THREAD

**Issue by tonykaram1993** [auth0/node-jsonwebtoken#927]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Basically whenever I try to run `jsonwebtoken.sign()` in typescript it gives me an error. Running the code is a simple javascript code runner works perfectly fine.

I have been trying to debug this for a couple of days now, can't seem to figure it out.

### Reproduction

Code to link I am working with: https://github.com/tonykaram1993/typescript-express-starter/blob/e6975e805f7f5b332e389d723d63a5641959ce15/src/services/authentication.services.ts#L64

The error log and a couple of log messages above it so you are able to see what is passed:
```
[watch] 
[watch] 
[watch] 2:42:24 PM - Found 0 errors. Watching for file changes.
[server] info: Server is running at https://localhost:5000
[server] info: Connected to MongoDB! [mongodb://localhost:27017/typescript]
[server] TKCL - JWT_TOKEN_SECRET: secretsecretsecretsecretsecretsecretsecret
[server] TKCL - data: {
[server]   email: 'john@thedoes.com',
[server]   passwordHash: '$2b$10$E.w9gKA4KsZU1LdN0KN99eCvAyteG/.xboV.ppGoh3gmiVWsJPyIi',
[server]   salt: '$2b$10$E.w9gKA4KsZU1LdN0KN99e',
[server]   _id: new ObjectId("64cf8723a2210d51f1731e86"),
[server]   __v: 0
[server] }
[server] TKCL - settingsConfig.AUTHENTICATION.jwtTokenExpiry: 1h
[server] POST /authentication/signup 500 72.621 ms - 1051
[server] POST /authentication/signup 500 72.621 ms - 1051
[server] TypeError: validator.isValid is not a function
[server]     at /Users/tk/Repositories/typescript-starter/node_modules/jsonwebtoken/sign.js:49:22
[server]     at Array.forEach (<anonymous>)
[server]     at validate (/Users/tk/Repositories/typescript-starter/node_modules/jsonwebtoken/sign.js:41:6)
[server]     at validatePayload (/Users/tk/Repositories/typescript-starter/node_modules/jsonwebtoken/sign.js:60:10)
[server]     at Object.module.exports [as sign] (/Users/tk/Repositories/typescript-starter/node_modules/jsonwebtoken/sign.js:138:7)
[server]     at Object.generateJwtToken (/Users/tk/Repositories/typescript-starter/dist/src/services/authentication.services.js:31:45)
[server]     at signup (/Users/tk/Repositories/typescript-starter/dist/src/controllers/authentication.controllers.js:29:56)
[server]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Environment

Library version:
```
"@types/jsonwebtoken": "^9.0.2",
"jsonwebtoken": "^9.0.1",
```

Express version:
```
"express": "^4.18.2",
    "@types/express": "^4.17.14",
```

Running macOs 13.4.1 on MacBook Pro  16" M1 Pro.

Happy to answer any questions.

**Comment by tonykaram1993** [comment]
Bump!

**Comment by tonykaram1993** [comment]
Alright, so I have an update regarding this.

I have been debugging for a week now (on and off), and I found something.

When I remove the following line https://github.com/tonykaram1993/typescript-express-starter/blob/feature/authentication/src/services/authentication.services.ts#L3C1-L3C38 - basically stop using lodash in the file where `jsonwebtoken.sign` is called, everything works totally fine.

So importing `lodash` breaks `jsonwebtoken`? Did I do something wrong that I need to change?

**Comment by tonykaram1993** [comment]
Alright, so scratch everything I said. It turned out to be that when I was getting the user (at https://github.com/tonykaram1993/typescript-express-starter/blob/feature/authentication/src/controllers/authentication.controllers.ts#L50C60-L50C60), I was getting a MongoDb Document instead of a plain object. 

All I did was to transform it into an object using `user.toObject()`. But it's weird that the error given by jsonwebtoken was not clear. I should have gotten the `payload is not a plain object` error instead of `validator.isValid` is not a function error.

I am not sure if this should be marked as resolved or if I should keep it open? I will leave that up to you guys.
